# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 765ac845d4ae8ccdfbe0b6e85ff6bd37633298173e0c1171aea7ad7e0ac8bbaf8d0d3a5c1ccb7cff315cfdc65a11e5c030fe66de71e0244403ccb069ba03312a

test:
  secret_key_base: d9bd3a308bc1f6c62c7ee500ad9e89260d903f5a35d3fd392ca90f7131f3f7ec76905743096c66632e325d811eb86662fde65863348c0a01b43d214ea8ebe3fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>